# Port name of the serial port
port_name: '/dev/ttyUSB0'
# Baud rate of the serial connection
baud_rate: 38400
# Wait time between each measures
wait_time: 1000
# Number of measures to take for calibration
nb_measure_calibration: 10
# Do calibration
do_calibration: True
